language: go

env:
  - GO111MODULE=on

sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev
  - sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

notifications:
  email: false
